// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsabJaYdyQOH2oahYRXRhY1KAE5LSZQ8Q',
    appId: '1:103165477696:web:6eb785d65086cc67e8b0e2',
    messagingSenderId: '103165477696',
    projectId: 'maprealtime-2e8d8',
    authDomain: 'maprealtime-2e8d8.firebaseapp.com',
    storageBucket: 'maprealtime-2e8d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsabJaYdyQOH2oahYRXRhY1KAE5LSZQ8Q',
    appId: '1:103165477696:android:e4018d8459f4f2d55530a5',
    messagingSenderId: '103165477696',
    projectId: 'maprealtime-2e8d8',
    storageBucket: 'maprealtime-2e8d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsabJaYdyQOH2oahYRXRhY1KAE5LSZQ8Q',
    appId: '1:103165477696:ios:66666bfa5b0410f2e8b0e2',
    messagingSenderId: '103165477696',
    projectId: 'maprealtime-2e8d8',
    storageBucket: 'maprealtime-2e8d8.appspot.com',
    iosBundleId: 'com.example.maprealtime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsabJaYdyQOH2oahYRXRhY1KAE5LSZQ8Q',
    appId: '1:103165477696:web:5dd580134bf46b30e8b0e2',
    messagingSenderId: '103165477696',
    projectId: 'maprealtime-2e8d8',
    authDomain: 'maprealtime-2e8d8.firebaseapp.com',
    storageBucket: 'maprealtime-2e8d8.appspot.com',
  );
}
